---
# tasks file for tomcat
    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install Java 17
      ansible.builtin.dnf:
        name: java-17-amazon-corretto-devel
        state: latest

    - name: Ensure group "tomcat group" exists
      group:
        name: tomcat
        state: present


    - name: Add the user 'tomcat' with a no login  shell, and the user tomcat to tomcat group
      user:
        name: tomcat
        shell: /bin/false
        home: /opt/tomcat
        group: tomcat


    - name: Create a tomcat directory if it does not exist and grant the directory permission
      file:
        path: /opt/tomcat
        state: directory
        mode:  '0755'
        owner: tomcat
        group: tomcat
        recurse: yes


    - name: Download tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
        dest: /opt/tomcat


    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src:  /opt/tomcat/apache-tomcat-9.0.76.tar.gz
        dest: /opt/tomcat/
        remote_src: yes
        mode: 0755
        owner: tomcat
        group: tomcat


    - name: Remove file (delete file)
      file:
        path: /opt/tomcat/apache-tomcat-9.0.76.tar.gz
        state: absent



    - name: copy tomcat-users.xml to tomcat_home/conf
      copy:
        src: roles/tomcat/files/tomcat-users.xml
        dest: /opt/tomcat/apache-tomcat-9.0.76/conf/
        remote_src: no
        owner: tomcat
        group: tomcat
        mode: 0755


    - name: copy context.xml to tomcat_home/meta-inf
      copy:
        src: roles/tomcat/files/context.xml
        dest: /opt/tomcat/apache-tomcat-9.0.76/webapps/manager/META-INF/context.xml
        remote_src: no
        owner: tomcat
        group: tomcat
        mode: 0755



    - name: copy tomcat service to systemd
      copy:
        src: roles/tomcat/files/tomcat.service
        dest: /etc/systemd/system/
        remote_src: no
        owner: root
        group: root
        mode: 0755



    - name: reload tomcat service
      systemd:
        daemon_reload: yes

    - name: Start tomcat service
      service:
        name: tomcat.service
        state: started

    - name: Start tomcat service
      service:
        name: tomcat.service
        enabled: yes


    - name: download jenkins
      get_url:
        url: https://get.jenkins.io/war/2.417/jenkins.war
        dest: /opt/tomcat/apache-tomcat-9.0.76/webapps
        owner: root
        group: root
        mode: 0755



